package com.github.darvld.krpc.compiler.generators

import com.github.darvld.krpc.SerializationProvider
import com.github.darvld.krpc.compiler.UnitClassName
import com.github.darvld.krpc.compiler.addClass
import com.github.darvld.krpc.compiler.buildFile
import com.github.darvld.krpc.compiler.markAsGenerated
import com.github.darvld.krpc.compiler.model.ServiceDefinition
import com.github.darvld.krpc.compiler.model.ServiceMethodDefinition
import com.squareup.kotlinpoet.*
import com.squareup.kotlinpoet.ParameterizedTypeName.Companion.parameterizedBy
import io.grpc.MethodDescriptor
import java.io.OutputStream

/**The name of the [SerializationProvider] parameter used in the constructor and as a property.*/
const val SERIALIZATION_PROVIDER_PARAM = "serializationProvider"

/**The name of the generated marshaller for this type.*/
private inline val ClassName.marshallerPropName: String
    get() = "${simpleName.replaceFirstChar { it.lowercaseChar() }}Marshaller"

/**Generate a helper class containing descriptors and marshallers required to implement a [service]. The class is
 * written to a file through [output].
 *
 * @see generateServiceProviderBase
 * @see generateClientImplementation*/
fun generateDescriptorContainer(output: OutputStream, service: ServiceDefinition) {
    buildFile(service.packageName, service.descriptorName, output) {
        addClass {
            addModifiers(KModifier.INTERNAL)
            markAsGenerated()

            addKdoc(
                "Internal helper class generated by the Krpc compiler," +
                        " This class is intended to be used only by generated declarations and should not" +
                        " be used in general code.\n\n" +
                        "@param $SERIALIZATION_PROVIDER_PARAM A provider implementing a serialization format." +
                        " Used to generate marshallers for rpc methods."
            )

            // Constructor with serialization provider as parameter (used to initialized method descriptors)
            primaryConstructor(
                FunSpec.constructorBuilder()
                    .addParameter(SERIALIZATION_PROVIDER_PARAM, SerializationProvider::class)
                    .build()
            )

            // Necessary for the `serializer` calls
            addImport("kotlinx.serialization", "serializer")

            // Generate helper method definitions
            service.methods.forEach {
                addServiceMethodDescriptor(it)
            }
        }
    }
}

/**Add a marshaller implementation for the given [typeName] to the descriptor container, using the serializationProvider.*/
private fun TypeSpec.Builder.addMarshaller(typeName: ClassName): String {
    // Don't generate a marshaller for Unit
    if (typeName == UnitClassName)
        return "SerializationProvider.UnitSerializer"

    val propName = typeName.marshallerPropName

    // Avoid re-generating the same marshaller
    propertySpecs.find { it.name == propName }?.let { return propName }

    val marshallerType = MethodDescriptor.Marshaller::class.asTypeName()
        .parameterizedBy(typeName)

    PropertySpec.builder(propName, marshallerType, KModifier.PRIVATE)
        .markAsGenerated()
        .addKdoc(
            """
            |A generated [MethodDescriptor.Marshaller] obtained using the serializationProvider constructor param.
            |""".trimMargin(),
        )
        .mutable(false)
        .initializer("$SERIALIZATION_PROVIDER_PARAM.marshallerFor(serializer())")
        .build()
        .also(::addProperty)

    return propName
}

/**Add a method descriptor to the container.*/
private fun TypeSpec.Builder.addServiceMethodDescriptor(
    definition: ServiceMethodDefinition
) {
    val requestType = definition.request.second
    val responseType = definition.returnType

    val type = MethodDescriptor::class.asTypeName()
        .parameterizedBy(requestType, responseType)

    PropertySpec.builder(definition.declaredName, type)
        .addKdoc(
            """
            |A generated [MethodDescriptor] for the [%L] service method.
            |
            |This descriptor is used by generated client and server implementations. It should not be
            |used in general code.
            |""".trimMargin(),
            definition.declaredName
        )
        .markAsGenerated()
        .mutable(false)
        .initializer(
            """
                |MethodDescriptor.newBuilder<%T,%T>()
                |    .setFullMethodName(%S)
                |    .setType(%L)
                |    .setRequestMarshaller(%L)
                |    .setResponseMarshaller(%L)
                |    .build()
                |""".trimMargin(),
            requestType,
            responseType,
            definition.methodName, // The "official" name for this method in the GRPC definition
            "MethodDescriptor.MethodType.${definition.methodType.name}", // The appropriate enum entry
            addMarshaller(requestType),
            addMarshaller(responseType)
        )
        .build()
        .let(::addProperty)
}