package com.github.darvld.krpc

/**Marker for kRPC service definitions. This annotation serves as an entry point for the kRPC symbol processor.
 *
 * See the annotation arguments for customization options.
 *
 * Service definitions must be interfaces containing only methods annotated with @[UnaryCall], @[ServerStream],
 * @[ClientStream] or @[BidiStream], and complying with the corresponding signatures. Any other method will cause
 * a processing error.*/
@Target(AnnotationTarget.CLASS)
@Retention(AnnotationRetention.SOURCE)
annotation class Service(
    /**Sets the name of this service within gRPC, if none is specified, the name of the interface is used.*/
    val overrideName: String = "",
    /**Sets the name of the abstract server implementation generated by the compiler. If not specified, the
     * interface name is used in the format "${interfaceName}Provider"*/
    val providerName: String = "",
    /**Sets the name of the client implementation generated by the compiler. If not specified, the
     * interface name is used in the format "${interfaceName}Client", removing any "Service" suffix on the original name.*/
    val clientName: String = ""
)