/*
 *    Copyright 2021 Dario Valdespino.
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */

package io.github.darvld.krpc.compiler.dsl

import com.squareup.kotlinpoet.*
import io.github.darvld.krpc.Generated


private val generatedAnnotationSpec = AnnotationSpec.builder(Generated::class)
    .addMember("\"io.github.darvld.krpc\"")
    .build()

/**Marks this type as generated by the kRPC compiler.*/
fun TypeSpec.Builder.markAsGenerated(): TypeSpec.Builder {
    return apply {
        addAnnotation(generatedAnnotationSpec)
    }
}

/**Marks this function as generated by the kRPC compiler.*/
fun FunSpec.Builder.markAsGenerated(): FunSpec.Builder {
    return apply {
        addAnnotation(generatedAnnotationSpec)
    }
}

/**Marks this property as generated by the kRPC compiler.*/
fun PropertySpec.Builder.markAsGenerated(): PropertySpec.Builder {
    return apply {
        addAnnotation(generatedAnnotationSpec)
    }
}
